Bookshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import (
    ContactUsView,
    ProductDetailView,
    ProductListView,

)


app_name = 'core'


urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('contact/', ContactUsView.as_view(), name='contact'),
    path('products/<slug:tag>/', ProductListView.as_view(), name='product_list'),
    path('product/<slug:slug>/', ProductDetailView.as_view(), name='product_detail')
]

core/models.py
from django.db import models
from django.db.models.fields import SlugField

class ActiveManager(models.Manager):
    def active(self):
        return self.filter(active=True)

class ProductTagManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug=SlugField)

class ProductTag(models.Model):
    name = models.CharField(max_length=32)
    slug = models.SlugField(max_length=48)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)

    objects = ProductTagManager()

    def __str__(self):
        return str(self.name)

    def natural_key(self):
        return (self.slug,)

class Product(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    price=models.DecimalField(max_digits=6, decimal_places=2, null=True)
    slug = models.SlugField(max_length=48)
    active = models.BooleanField(default=True)
    tags = models.ManyToManyField(ProductTag, blank=True)
    in_stock = models.BooleanField(default=True)
    date_updated =  models.DateTimeField(auto_now=True)

    # custom managers
    objects = ActiveManager()

    def __str__(self):
        return str(self.name)

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product-images')
    thumbnail = models.ImageField(upload_to='product-thumbnails', null=True)

    def __str__(self):
        return str(self.product.name) + '-image'

core/forms.py
from django import forms
import logging
from django.core.mail import send_mail

from Bookshop.settings import DEBUG

logging.basicConfig(level=DEBUG)
logger = logging.getLogger(__name__)

class ContactForm(forms.Form):
    name = forms.CharField(label='Your name', max_length=100)
    message = forms.CharField(max_length=600, widget=forms.Textarea)


    def send_mail(self):
        logger.info("Sending email to customer service")
        message = f"From: {self.cleaned_data.get('name')}, {self.cleaned_data.get('message')}"

        send_mail(
            "Site message",
            message,
            "site@booktime.domain",
            ["customerserveic@booktime.domain"],
            fail_silently=False
        )

core/views.py
from typing import List
from django.shortcuts import get_object_or_404, redirect, render
from .forms import ContactForm
from .models import Product, ProductTag
from django.views.generic import FormView, ListView, DetailView, DeleteView

class ContactUsView(FormView):
    template_name = 'contact_form.html'
    form_class = ContactForm
    success_url = "/"

    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)

    def get_form_kwargs(self):
        print('#####')
        print(self.kwargs)
        return super().get_form_kwargs()



# View for listing out the products on the web page
class ProductListView(ListView):
    
    # template_name = 'products_list.html'
    context_object_name = 'products'
    paginate_by = 2
    def get_queryset(self):

        print(self.kwargs)  
        tag = self.kwargs['tag']
        self.tag = None

        if tag != 'all':
            self.tag = get_object_or_404(ProductTag, slug=tag)

        if self.tag:
            products = Product.objects.active().filter(
                tags = self.tag
            )
        else:
            products = Product.objects.active()


        return products

class ProductDetailView(DetailView):
    model = Product

core/templates/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock title %}

{% block content %}
    <h3>BookTime! best book retailer </h3>
    <p>Booktime is a company that sells books online.</p>

{% endblock content %}

core/templates/contact_form.html
{% extends 'base.html' %}

{% block title %}Contact Form{% endblock title %}

{% block content %}
<h1>{{title}}</h1>
    <!-- <form action="" method="POST">
        {% csrf_token %}
        {{form_fbv.as_p}}
        <input type="submit" value="Send Email">
    </form> -->

    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{form.name.label}}
            <input type="text"
            class="form-control {% if form.errors %}is-invalid{% endif %}"
            id="id_name"
            name="name"
            placeholder="Your name"
            value="{{ form.name.value|default:'' }}">
            {% if form.errors %}
                <div class="invalid-feedback">
                    {{form.name.errors}}
                </div>
            {% endif %}
            
        </div>
        <div class="form-group">
            {{form.message.label}}
            <textarea
            class="form-control {% if form.errors %}is-invalid{% endif %}"
            id="id_name"
            name="message"
            placeholder="Your message"
            row='5'>
            {{ form.message.value|default:'' }}
            </textarea>
            {% if form.errors %}
                <div class="invalid-feedback">
                    {{form.message.errors}}
                </div>
            {% endif %}
            
        </div>
        <input type="submit" value="Send Email">
    </form>
{% endblock content %}

core/templates/core/product_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>Products</h1>
    <table class="table">
        <tr>
            <th>Name</th>
            <td>{{object.name}}</td>
        </tr>
        <tr>
            <th>Cover images</th>
            <td>
                {% for image in object.productimage_set.all %}
                  <img src="{{image.thumbnail.url}}" alt="cover">
                {% endfor %}
            </td>
        </tr>
        <tr>
            <th>Price</th>
            <td>{{object.price}} this is the price</td>
        </tr>
        <tr>
            <th>Description</th>
            <td>{{object.description|linebreaks}}</td>
        </tr>
        <tr>
            <th>Tags</th>
            <td>{{object.tags.all|join:","|default:'No tags available'}}</td>
        </tr>
        <tr>
            <th>In stock</th>
            <td>{{ object.instock|yesno|capfirst}}</td>
        </tr>
        <tr>
            <td>Updated</td>
            <td>{{object.date_updated|date:"F Y" }}</td>
        </tr>
    </table>
    <a href="#">Add to basket</a>
{% endblock content %}

core/templates/core/product_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>This is the list of available products </h1>
    <div class="row">
        <div class="col-md-2 bg-dark white">
            <p class="text-white">this is the navigation for the list view</p>
            <p class="text-white"><a href="{% url 'core:product_list' 'all' %}">All</a></p>
            <p class="text-white"><a href="{% url 'core:product_list' 'drama' %}">Drama</a></p>
            <p class="text-white"><a href="{% url 'core:product_list' 'romance' %}">Romance</a></p>
            <p class="text-white"><a href="{% url 'core:product_list' 'programming' %}">Programming</a></p>
        </div>
        <div class="col-md-10">
            <p class="lead">Here are list of all products</p>
            {% for product in page_obj %}
              <p>{{product.name}}</p>
              <p>
                  <a href="{% url 'core:product_detail' product.slug %}">See it here</a>
              </p>
              {% if not forloop.last %}
                <hr>
              {% endif %}
            {% endfor %}

            <nav>
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                      <li class="page-item">
                          <a href="?page={{page_obj.previous_page_number}}" class="page-link">Previous</a>
                      </li>
                    {% else %}
                      <li class="page-item disabled">
                          <a href="#" class="page-link">Previous</a>
                      </li>
                    {% endif %}

                    {% for pagenum in page_obj.paginator.page_range %}
                      <li 
                        class="page-item {% if page_obj.number == pagenum %}active{% endif %}">
                            <a href="?page={{pagenum}}" class="page-link">
                                {{pagenum}}</a>                            
                        </li>
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a href="?page={{page_obj.next_page_number}}" class="page-link">Next</a>
                        </li>
                    {% else %}
                        <div class="page-item disabled">
                            <a href="#" class="page-link">Next</a>
                        </div>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
{% endblock content %}

core/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h1>This is the test of the home page BookTime</h1>
{% endblock content %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <title>BookTime-{% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include './utils/navigation.html' %}
    <div class="container">
    {% block content %}{% endblock content %}
    </div>
    
    <script src="{% static 'js/jquery-3.6.0.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/utils/navigation.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link {% if request.path == '/' %} active {% endif %}" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link{% if request.path == '/about/' %} active {% endif %}" href="/about/">About us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link{% if request.path == '/contact/' %} active {% endif %}" href="/contact/">Contact us</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>